### ISSUE TITLE
OneOf handling does not convert correctly when the set value matches a datatype default

### ISSUE THREAD

**Issue by jdevalk2** [blueapron/kafka-connect-protobuf-converter#10]
When serializing a protobuf format that has a oneof field definition like this:

message Telemetry {
	string test = 1;
	map<string, AttributeValue> attributeValues = 2;
}

message AttributeValue {
    oneof ValueOneOf {
        int32 int = 1;
	int64 long = 2;
        double double = 3;
        bool boolean = 4;
        string string = 5;
        int64 timestamp = 6;
    }
}

One obvious case where it can be seen go wrong is boolean. When the value of the original protocol buffer message is set to False, then this matches the boolean default, which is false. Then subsequently "Null" value will be serialized. In effect from a set boolean value we went to none of the values in the oneof collection being set.

I traced the cause to ProtobufData, 
Object toConnectData(Schema schema, Object value)  method.

Struct handling.

The following patch fixes the issue, it introspects the protocol buffer metadata and writes the oneof field value instead of relying on whether the value equals the datatype default.

(Note the patch is not complete as it does not check for if none of the OneOf values is set (all of the fields would have no value in this case), which is a possibility. Also it only considers Protobuf -> Connect conversion, I have not tested the other way around from Connect->ProtoBuf)

```

 case STRUCT: {
          final Message message = (Message) value; // Validate type
          if (message == message.getDefaultInstanceForType()) {
            return null;
          }

          final Struct result = new Struct(schema.schema());

          for (Descriptors.FieldDescriptor fieldDescriptor : message.getDescriptorForType().getFields()) {

            Descriptors.OneofDescriptor oneOfDescriptor = fieldDescriptor.getContainingOneof();
            if (oneOfDescriptor != null) {
              Descriptors.FieldDescriptor oneFieldDescriptor = message.getOneofFieldDescriptor(oneOfDescriptor);

              String oneFieldName = getConnectFieldName(oneFieldDescriptor);
              Field oneField = schema.field(oneFieldName);
              Object oneValue = message.getField(oneFieldDescriptor);

              result.put(oneFieldName, toConnectData(oneField.schema(), oneValue));
              break; // Can only be one field set
            }
            else {
              final String fieldName = getConnectFieldName(fieldDescriptor);
              final Field field = schema.field(fieldName);
              Object obj = message.getField(fieldDescriptor);
              result.put(fieldName, toConnectData(field.schema(), obj));
            }
          }

          converted = result;
          break;
        }

        default:
          throw new DataException("Unknown Connect schema type: " + schema.type());

  
```

**Comment by jdevalk2** [comment]
With regards to the updated version, I noticed right now there is no publish to a public Maven repository.

It would be cool if the JAR with dependencies can be pulled from a public Maven repo, as the other options are compiling it as part of our own build or compiling it once and treating it as external dependency. Both requiring some "ownership" of the code, while I am just interested in the binaries.

Any plans on the roadmap to publish to Maven?

**Comment by makearl** [comment]
We would love to publish this to Maven, but we have no plans for that on the near-term roadmap
