### ISSUE TITLE
Protobuf Map Type is not mapped to Kafka Connect Schema Map type

### ISSUE THREAD

**Issue by ofirski** [blueapron/kafka-connect-protobuf-converter#47]
Kafka Connect Schema supports [Map types](https://kafka.apache.org/11/javadoc/org/apache/kafka/connect/data/Schema.Type.html#MAP), but it appears that the maintainers of this converter took a design decision to convert fields with Protobuf Map type to an Array of Struct with two fields: key & value as documented in this [PR](https://github.com/blueapron/kafka-connect-protobuf-converter/pull/1).

This creates an issue when trying to parse the result of such conversion with Protobuf frameworks such as Google's protobuf for python.

Consider the following proto as example:
```
message MessageWithMapProto {
    string user_id = 1;
    bool is_active = 2;
    map<string,string> user_mapping = 3;
}
```
The result of `toConnectData` on an instance of such message would be:
```
SchemaAndValue{
   schema=Schema{MessageWithMapProto:STRUCT}, 
   value=Struct{user_id=123,
                is_active=true,
                user_mapping=[Struct{key=a,value=1}, Struct{key=b,value=2}]
   }
}
```

After conversion we later store this data in an ORC format which preserves the Kafka Connect Schema and when trying to read the stored data it cannot be parsed back into the original Protobuf message format as the parser expects a map and instead an array is provided.

Since changing the output of the converter is a breaking change, I suggest to add a configuration that will set Map type conversion mode (default: `LIST_OF_STRUCT`, `MAP`), while preserving backwards compatibility and providing support for users who would like to get the standard Connect Schema Map type.

Please let me know if it makes sense and I'll submit a PR to add such change.

**Comment by rotemtam** [comment]
@mike9005 WDYT?

**Comment by mike9005** [comment]
@ofirski nice idea - I think that's a good compromise - please do submit a PR.

For context, some of the initial design decisions here were based on our internal use case (which was only Proto -> Connect Schema, not the reverse), but happy to reassess now that more folks are using this - anything else you notice like this, we'd be keen to hear - thanks!

**Comment by bagipriyank** [comment]
@ofirski I tried using the config `value.converter.protoMapConversionType=map` however `map<string,string>` is still getting converted to `array<struct<key:string,value:string>>` on conversion to parquet when using kafka-connect-s3 sink connector. (https://github.com/confluentinc/kafka-connect-storage-cloud/issues/326)

I think it's happening because of `schema.keySchema().isOptional()` at https://github.com/confluentinc/schema-registry/blob/master/avro-data/src/main/java/io/confluent/connect/avro/AvroData.java#L502

I am not sure if that is something that needs to change here or change in kafka schema registry. Or maybe I am missing something.

**Comment by ofirski** [comment]
Hi @bagipriyank,
The converter converts protobuf byte representation into Kafka Connect internal representation, so map<string, string> should convert to Map<String, String> and that is passed forward to the sink. To isolate if the issue is in the converter or in the sink, I suggest replacing the current sink you are using into a simple FileSink and check if the output is actually a map or an array of structs.

Please share your findings.

**Comment by bayardneville** [comment]
Closing this issue since the related PR was merged.
