### ISSUE TITLE
Please release latest version to Confluent Hub

### ISSUE THREAD

**Issue by hargab** [blueapron/kafka-connect-protobuf-converter#48]
Hi,
3.0.0 fixes a bug for me that is present in 2.0.0 however the latest and only version on Confluent Hub is 2.0.0, so I have to download the jar and it’s dependencies manually. Could you please upload 3.0.0

Thanks

**Comment by mike9005** [comment]
Hi there - we will get this put on Confluent Hub shortly with the next 3.x release we're preparing now. In the meantime, all the releases are available on Maven Central - https://mvnrepository.com/artifact/com.blueapron/kafka-connect-protobuf-converter/3.0.0

**Comment by hargab** [comment]
Hi,
Thanks. Yeah, I can grab it from Maven but it is a bit more hassle to get it from there. 

Thanks,
Gabor

**Comment by mike9005** [comment]
We sent the latest 3.1.0 artifact to Confluent yesterday for additional to Hub - unfortunately they require you email it to them and it's manually uploaded, so can't give you an ETA, but hopefully in the next couple of days. 🙏

**Comment by normzeng** [comment]
@hargab 3.1.0 is now in [Confluent Hub](https://www.confluent.io/hub/blueapron/kafka-connect-protobuf-converter) Let me know if there are any issues. Closing this for now.
