### ISSUE TITLE
Where to put the protoClass jar ?

### ISSUE THREAD

**Issue by mugugnu** [blueapron/kafka-connect-protobuf-converter#59]
hello,
i'm trying to configure kafkaconnect (in kubernetes pod) to deserialize protobuf data in a specific topic.
I've already put the ProtobufConverter jars in kafka plugin directory.
When i load the sink connector, I'm getting a "org.apache.kafka.connect.errors.ConnectException: Proto class com.cloudflare.net.flowagg.FlowMessagePb not found in the classpath" error

Where am i supposed to put the compiled proto jar for the connector to find it ?
I've also tried to create the /usr/share/java/kafka-serde-tools directory and put the jar there with no luck, but the fact that i don't have that dir in my kafkaconnect pod makes me think it was just an example..

My connector converter settings looks like:

    value.converter: "com.blueapron.connect.protobuf.ProtobufConverter"
    value.converter.protoClassName: "com.cloudflare.net.flowagg.FlowMessagePb"
    key.converter: "com.blueapron.connect.protobuf.ProtobufConverter"

**Comment by mugugnu** [comment]
Hi, any help appreciated, i'm still out in the woods!

**Comment by bayardneville** [comment]
Have you tried putting the proto jar in the same location as the the protobuf converter jar?

**Comment by mugugnu** [comment]
Hi,
Yes I tried to put them both in /opt/kafka/libs..same result, and tried in /opt kafka/plugins (which did not make much sense to me) with no luck. I also tried to put the converter in /opt/kafka/libs and the proto class jar in /opt/kafka/plugins, same results as well.
I am running out of options. I don't quite get if the proto class jar is actually needed by the protobuf converter or by the plugin, if it's the former, which I think is, what's the classpath it's using? And more: does it need a compiled proto class jar (with .classes in it) or a non compiled one ( with .java in it)? I assume the former but I am starting to not take anything for granted..

Any help very much appreciated,
Regards,
Mugugnu

________________________________

**Comment by mugugnu** [comment]
Update: i skipped the issue by adding my proto compiled class as a dependency for the converter maven project. I still need to double check if it was just a simple matter of how i built the compiled class jar and the paths inside it, because when adding it to the maven  protobuf project i might have changed it.

**Comment by fsouza-bux** [comment]
hi @mugugnu , could you detail the path you're using now for your proto classes? We are passing through the same issue. One difference, we are adding on our pom.xml the dependency for the blueapron converter:
```
    <dependency>
      <groupId>com.blueapron</groupId>
      <artifactId>kafka-connect-protobuf-converter</artifactId>
      <version>3.1.0</version>
    </dependency>
```
